name: Xray Config Collector

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: Initialize Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Collector
        run: go run main.go

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 1. Temporarily 'hide' the new configs Go generated
          git add .
          git stash
          
          # 2. Sync with the remote repository
          git pull --rebase origin main
          
          # 3. Bring the new configs back into the folder
          git stash pop || echo "No changes to merge"
          
          # 4. Finalize the commit
          git add .
          git commit -m "Update configs $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push origin main
